"CREATE TABLE `dwd_sr_order_promotion_order` (
  `auto_id` bigint(20) NOT NULL COMMENT ""自增ID"",
  `dt` date NOT NULL COMMENT ""创建日期"",
  `create_time` datetime NULL COMMENT ""创建时间"",
  `update_time` datetime NULL COMMENT ""更新时间"",
  `order_id` varchar(255) NULL COMMENT ""订单ID"",
  `user_id` int(11) NULL COMMENT ""用户ID"",
  `merchant_id` int(11) NULL COMMENT ""商家ID"",
  `store_id` int(11) NULL COMMENT ""店铺ID"",
  `eleme_auth_store_id` int(11) NULL COMMENT ""饿了么授权店铺ID"",
  `meituan_auth_store_id` bigint(20) NULL COMMENT ""美团授权店铺ID"",
  `phone` varchar(255) NULL COMMENT ""用户手机号"",
  `eleme_user_id` varchar(255) NULL COMMENT ""饿了么用户ID"",
  `store_promotion_id` int(11) NULL COMMENT ""店铺活动ID"",
  `store_platform_type` int(11) NULL COMMENT ""店铺平台ID(1:美团,2:饿了么)"",
  `merchant_rebate_amt` decimal(12, 2) NULL COMMENT ""商家返利金额"",
  `order_amt` decimal(12, 2) NULL COMMENT ""订单金额"",
  `real_rebate_amt` decimal(12, 2) NULL COMMENT ""实际返现金额"",
  `origin_rebate_amt` decimal(12, 2) NULL COMMENT ""原始返现金额"",
  `used_meal_ticket_num` int(11) NULL COMMENT ""使用餐券数"",
  `order_log` varchar(65533) NULL COMMENT ""订单日志"",
  `order_time` varchar(255) NULL COMMENT ""下单时间"",
  `create_time2` varchar(255) NULL COMMENT ""下单当天0点时间戳"",
  `rebate_condition_type` int(11) NULL COMMENT ""返利条件类型(0:5星好评,1:5星好评+10字评论;2:5星好评+10字评论+1图,3:5星好评+10字评论+2图,5:5星好评+10字评论+3图,6:5星好评+图,99:仅下单)"",
  `rebate_condition_desc` varchar(255) NULL COMMENT ""返利条件说明"",
  `platform_order_id` varchar(50) NULL COMMENT ""平台订单ID"",
  `platform_order_time` varchar(255) NULL COMMENT ""平台下单时间"",
  `user_pay_amt` decimal(12, 2) NULL COMMENT ""用户支付金额"",
  `platform_order_screenshot` varchar(65533) NULL COMMENT ""平台订单截图"",
  `platform_evaluation_order_screenshot_url` varchar(65533) NULL COMMENT ""平台评估订单截图地址"",
  `order_status` int(11) NULL COMMENT ""订单状态(0:已报名，待上传,1:待审核,2:已审核,3:驳回,4:手动取消,5:超时取消,6:自动审核中,7:管理员取消,8:已审核，但用户不满意,9:待复审,99:所有)"",
  `auth_order_status` int(11) NULL COMMENT ""授权订单状态"",
  `redpacket_amt` decimal(12, 2) NULL COMMENT ""小蚕红包金额"",
  `customer_service_audit_feedback` varchar(65533) NULL COMMENT ""客服审核反馈"",
  `auditor_id` int(11) NULL COMMENT ""审核人ID"",
  `platform_order_amt` varchar(255) NULL COMMENT ""平台订单下单金额(和user_pay_amt字段一致)"",
  `platform_order_store_name` varchar(1024) NULL COMMENT ""平台下单店铺名称"",
  `platform_order_detail` varchar(65533) NULL COMMENT ""平台订单详情"",
  `platform_order_rate_detail` varchar(65533) NULL COMMENT ""平台订单评价详情"",
  `deduct_candou_feedback` varchar(65533) NULL COMMENT ""扣减蚕豆反馈"",
  `auth_order_finish_time` varchar(255) NULL COMMENT ""授权订单完成时间"",
  `is_auto_audit` int(11) NULL COMMENT ""是否自动审核(0:否,1:是)"",
  `is_union_order` int(11) NULL COMMENT ""是否联盟(0:否,1:是)"",
  `profit` decimal(12, 2) NULL COMMENT ""利润"",
  `county_id` int(11) NULL COMMENT ""区县ID"",
  `city_id` int(11) NULL COMMENT ""城市ID"",
  `bd_id` int(11) NULL COMMENT ""商务ID"",
  `user_remark` varchar(65533) NULL COMMENT ""用户备注"",
  `order_type` int(11) NULL COMMENT ""用订单类型( 0:未知,1:超前点单,2:预订单,10, 饿了么返利小程序订单,11:cps,12:美团官方霸王餐,13:饿了么官方霸王餐)户ID"",
  `order_submit_audit_time` varchar(255) NULL COMMENT ""订单提交审核时间"",
  `order_audit_finish_time` varchar(255) NULL COMMENT ""订单审核完成时间"",
  `platform_pic_ocr_result` varchar(65533) NULL COMMENT ""平台识别图片文本结果"",
  `is_vip_auto_audit_order` int(11) NULL COMMENT ""是否vip自动审核订单(0:否,1:是)"",
  `is_vip_exclusive_order` int(11) NULL COMMENT ""是否vip专享活动订单(0:否,1:是)"",
  `order_platform` int(11) NULL COMMENT ""下单平台(0:H5,1:小程序,2:APP)"",
  `ip_county_id` int(11) NULL COMMENT ""IP区县ID"",
  `is_platform_recognize_order_screenshot` int(11) NULL COMMENT ""平台是否成功识别订单截图(-1:未通过自动审核,-2:未通过自动审核0:未通过自动审核,1:已通过自动审核,2:已通过自动审核,3:已通过自动审核,4:已通过自动审核,5:已通过自动审核)"",
  `promotion_rebate_type` int(11) NULL COMMENT ""活动返利类型(0:霸王餐,1:返利餐)"",
  `user_ip` varchar(255) NULL COMMENT ""用户IP"",
  `user_location` varchar(65533) NULL COMMENT ""用户位置"",
  `foreigner_store` varchar(255) NULL COMMENT ""外部店铺"",
  `order_timeout_time` varchar(255) NULL COMMENT ""订单超时时间"",
  `broker_msg_id` varchar(255) NULL COMMENT ""消息代理ID"",
  `service_charge` decimal(12, 2) NULL COMMENT ""服务费"",
  `audit_reason_type` int(11) NULL COMMENT ""驳回原因类型(0:,1:需要商家确认,2:需要用户录屏,3:其他,4:订单号不一致,5:未显示订单号,6:店铺名称不一致,7:没有店铺名称 ,8:下单时间不一致 ,9:没有下单时间 ,10:没有支付金额 ,11:未显示订单已完成 ,12:没有评价 ,13:评价非五星 ,14:评价图不完整 ,15:评价未带图 ,16:实付不满 ,17:部分退款 ,18:评价截图位置不对 ,19:评价不真实 ,20:审核通过新增：实付不满/部分退款 ,21:审核驳回新增：评价未带字（美团/饿了么） ,22:审核驳回新增：取消订单/全部退款 ,23:转复审新增：用户不同城区下单 ,24:转复审新增：大额返现，进入人工 ,25:转复审新增：用户今日超过三单 ,26:转复审新增：疑似P图 ,27:通过（不满意）新增：评价非五星 ,28:通过（不满意）新增：评价文字不满意 ,29:美团点评实物圈折鹽掉 ,30:检测用户有退款 ,31:订单号上传错误 ,32:点评截图不是本家 ,33:点评截图未提交页面 ,34:评价未带字（饿了么） ,35:评价未带字（美团） ,36:星星未显示 ,37:最终实付不符合活动要求 ,38:汀単截圏不完整 ,39:预订单 ,40:用餐反馈时间不一致)"",
  `notify_time` varchar(255) NULL COMMENT ""提醒时间"",
  `operate_broker_msg_id` varchar(255) NULL COMMENT ""操作消息代理ID"",
  `platform_order_store_name2` varchar(512) NULL COMMENT ""平台订单店铺名称"",
  `customer_service_interior_remark` varchar(65533) NULL COMMENT ""客服内部备注"",
  `is_merchant_confirm` int(11) NULL COMMENT ""是否需要商家确认(0:否,1:是)"",
  `merchant_confirm_status` int(11) NULL COMMENT ""商家确认状态(0:未知,1:等待确认,2:已确认,3:已驳回（无此订单）)"",
  `is_sham_order` int(11) NULL COMMENT ""是否虚假订单(0:否,1:是)"",
  `deduct_candou_num` decimal(12, 2) NULL COMMENT ""扣减蚕豆数"",
  `platform_order_status` int(11) NULL COMMENT ""平台订单状态(0:,1:,2:,3:,4:)"",
  `platform_evaluation_order_screenshot_result` varchar(255) NULL COMMENT ""平台评估订单截图结果"",
  `is_success_recognize_order_screenshot` int(11) NULL COMMENT ""是否成功识别订单截图(0:否,1:是)"",
  `channel_expend` decimal(12, 2) NULL COMMENT ""渠道花费"",
  `is_submit_exception_order` int(11) NULL COMMENT ""是否提交过异常订单(0:否,1:是)"",
  `merchant_pay_amt` decimal(12, 2) NULL COMMENT ""商家支付金额"",
  `exception_order_merchant_deduct_amt` decimal(12, 2) NULL COMMENT ""异常订单商家扣减金额"",
  `merchant_pay_status` int(11) NULL COMMENT ""商家付款状态(0:暂未支付,1:已支付)"",
  `is_operation_activity` int(11) NULL COMMENT ""是否运营活动(0:否,1:是)"",
  `if_user_deleted` int(11) NULL COMMENT ""是否用户侧删除""
) ENGINE=OLAP 
PRIMARY KEY(`auto_id`, `dt`)
COMMENT ""订单表""
PARTITION BY date_trunc('day', dt)
DISTRIBUTED BY HASH(`auto_id`, `dt`)
ORDER BY(`auto_id`, `dt`)
PROPERTIES (
""compression"" = ""LZ4"",
""enable_persistent_index"" = ""true"",
""fast_schema_evolution"" = ""false"",
""replicated_storage"" = ""true"",
""replication_num"" = ""3""
);"




"CREATE TABLE `dwd_sr_store_promotion` (
  `store_promotion_id` bigint(20) NOT NULL COMMENT ""店铺活动ID"",
  `dt` date NOT NULL COMMENT ""dt(分区字段)"",
  `create_time` datetime NULL COMMENT ""创建时间"",
  `update_time` datetime NULL COMMENT ""更新时间"",
  `merchant_id` int(11) NULL COMMENT ""商家ID"",
  `store_id` int(11) NULL COMMENT ""店铺ID"",
  `eleme_auth_store_id` int(11) NULL COMMENT ""饿了么授权店铺ID"",
  `meituan_auth_store_id` bigint(20) NULL COMMENT ""美团授权店铺ID"",
  `meituan_store_url` varchar(255) NULL COMMENT ""美团店铺URL"",
  `store_type` int(11) NULL COMMENT ""店铺类型(0:普通店铺1:优质店铺,2:大客户)"",
  `longitude` double NULL COMMENT ""经度"",
  `latitude` double NULL COMMENT ""纬度"",
  `meituan_status` int(11) NULL COMMENT ""美团状态(1:开启美团活动)"",
  `meituan_order_amt` decimal(12, 2) NULL COMMENT ""美团订单金额"",
  `meituan_mlabel_threshold_amt` decimal(12, 2) NULL COMMENT ""美团餐标门槛金额"",
  `meituan_promotion_quota` int(11) NULL COMMENT ""美团活动名额"",
  `meituan_promotion_remain_quota` int(11) NULL COMMENT ""美团活动剩余名额"",
  `meituan_upload_num` int(11) NULL COMMENT ""美团待上传数量"",
  `meituan_audit_num` int(11) NULL COMMENT ""美团待审核数量"",
  `meituan_finished_num` int(11) NULL COMMENT ""美团完成数量"",
  `meituan_mlabel_rebate_amt` decimal(12, 2) NULL COMMENT ""美团餐标返现金额"",
  `eleme_status` int(11) NULL COMMENT ""饿了么状态(1:开启饿了么活动)"",
  `eleme_order_amt` decimal(12, 2) NULL COMMENT ""饿了么订单金额"",
  `eleme_mlabel_threshold_amt` decimal(12, 2) NULL COMMENT ""饿了么餐标门槛金额"",
  `eleme_promotion_quota` int(11) NULL COMMENT ""饿了么活动名额数量"",
  `eleme_promotion_remain_quota` int(11) NULL COMMENT ""饿了么剩余名额数量"",
  `eleme_upload_num` int(11) NULL COMMENT ""饿了么待上传数量"",
  `eleme_audit_num` int(11) NULL COMMENT ""待审核数量"",
  `eleme_finished_num` int(11) NULL COMMENT ""饿了么完成数量"",
  `eleme_mlabel_rebate_amt` decimal(12, 2) NULL COMMENT ""饿了么餐标返现金额"",
  `estimate_rebate_amt` decimal(12, 2) NULL COMMENT ""预计商家返利金额"",
  `fact_rebate_amt` decimal(12, 2) NULL COMMENT ""实际返利"",
  `return_rebate_amt` decimal(12, 2) NULL COMMENT ""中途结算返还余额"",
  `balance_amt` decimal(12, 2) NULL COMMENT ""结余金额"",
  `fact_pay_rebate_amt` int(11) NULL COMMENT ""商家实际支付返利(计算实际返利时,取meituan_rebate或eleme_rebate字段,都有则取两个字段值中最大的)"",
  `begin_date` varchar(255) NULL COMMENT ""活动开始日期"",
  `end_date` varchar(255) NULL COMMENT ""活动结束日期"",
  `begin_time` varchar(255) NULL COMMENT ""活动开始日期时间戳"",
  `end_time` varchar(255) NULL COMMENT ""活动结束日期时间戳"",
  `begin_time_midnight` varchar(255) NULL COMMENT ""活动开始当天零点"",
  `end_time_midnight` varchar(255) NULL COMMENT ""活动结束当天零点"",
  `daily_begin_hour` int(11) NULL COMMENT ""每日开始小时"",
  `daily_begin_minute` int(11) NULL COMMENT ""每日开始分钟"",
  `daily_end_hour` int(11) NULL COMMENT ""每日结束小时"",
  `daily_end_minute` int(11) NULL COMMENT ""每日结束分钟"",
  `rebate_condition_type` int(11) NULL COMMENT ""返利条件类型(0:5星好评,1:5星好评+10字评论,2:5星好评+10字评论+1图,3:5星好评+10字评论+2图,4:5星好评+10字评论+3图,5:5星好评+10字评论+4图,6:5星好评+图,99:仅下单)"",
  `rebate_condition_desc` varchar(255) NULL COMMENT ""返利条件说明"",
  `remark` varchar(255) NULL COMMENT ""备注"",
  `used_meal_ticket_num` int(11) NULL COMMENT ""使用餐券数"",
  `service_charge` decimal(12, 2) NULL COMMENT ""服务费"",
  `status` int(11) NULL COMMENT ""状态(0:待审核,1:已审核,2:驳回,3:拉黑,4:商家手动结束,5:最终结束状态,99:所有)"",
  `reject_reason` varchar(255) NULL COMMENT ""驳回原因"",
  `auditor_id` int(11) NULL COMMENT ""后台审核人"",
  `manual_settle_time` int(11) NULL COMMENT ""商家手动结算时间"",
  `cooper_type` int(11) NULL COMMENT ""合作类型(0:未知,1:商家支付,2:用户扣除,3:品牌推广服务-公司承担,98:更改为不用开票,99:所有)"",
  `subscribe_num` int(11) NULL COMMENT ""订阅人数"",
  `pay_status` int(11) NULL COMMENT ""付款状态(0:商家已余额支付,1:后台创建活动开始,2:等待商家支付,3:支付完成,4:部分支付完成)"",
  `promotion_type` int(11) NULL COMMENT ""活动类型(1:余额支付活动,2:后台创建活动)"",
  `promotion_rebate_type` int(11) NULL COMMENT ""活动返利类型(0:霸王餐,1:返利餐)"",
  `finance_manual_settle_remark` varchar(255) NULL COMMENT ""财务手动结账备注"",
  `finance_manual_settle_pic_url` varchar(1000) NULL COMMENT ""财务手动结账账单截图URL"",
  `county_id` int(11) NULL COMMENT ""区县ID"",
  `city_id` int(11) NULL COMMENT ""城市ID"",
  `bd_id` int(11) NULL COMMENT ""商务负责人ID"",
  `is_virtual` int(11) NULL COMMENT ""是否虚拟活动(0:否,1:是)"",
  `is_miaosha` int(11) NULL COMMENT ""是否秒杀活动(0:否,1:是)"",
  `is_private` int(11) NULL COMMENT ""是否私有活动(0:否,1:是)"",
  `promotion_condition` varchar(255) NULL COMMENT ""参与活动条件"",
  `is_vip_exclusive` int(11) NULL COMMENT ""是否vip专享活动(0:否,1:是)"",
  `pay_time` varchar(255) NULL COMMENT ""付款时间"",
  `is_pay_exception` int(11) NULL COMMENT ""是否支付异常(异常指15天内未支付。0:否,1:是)"",
  `profit` decimal(12, 2) NULL COMMENT ""利润"",
  `modify_fact_rebate_amt` decimal(12, 2) NULL COMMENT ""修改商家实际支付返利"",
  `modify_fact_rebate_reason` varchar(255) NULL COMMENT ""修改实际返利原因"",
  `modify_fact_rebate_status` int(11) NULL COMMENT ""修改返利金额状态(0:默认,1:等待,2:反馈,3:拒绝)"",
  `bad_debt_time` varchar(255) NULL COMMENT ""坏账时间"",
  `pay_abnormal_status` int(11) NULL COMMENT ""坏账状态(0:默认,1:等待,2:完成)"",
  `is_youzhi_promotion` int(11) NULL COMMENT ""是否优质活动(0:否,1:是)"",
  `pay_method` int(11) NULL COMMENT ""付款方式(0:未知,1:微信支付,2:支付宝支付,3:微信收款码,4:支付宝收款码,5:对私银行,6:对公银行,7:用户余额支付)"",
  `promotion_tag` varchar(255) NULL COMMENT ""活动标签"",
  `is_invoiced` int(11) NULL COMMENT ""是否已开发票(0:否,1:是)"",
  `channel_expend` decimal(12, 2) NULL COMMENT ""渠道花费"",
  `order_deduct_amt` decimal(12, 2) NULL COMMENT ""订单扣减金额"",
  `is_operation_promption` int(11) NULL COMMENT ""是否运营活动(0:否,1:是)"",
  `audit_admin_id` int(11) NULL COMMENT ""后台审核管理人ID"",
  `bd_remark` varchar(255) NULL COMMENT ""bd备注"",
  `collection_amt` decimal(12, 2) NULL COMMENT ""部分收款金额"",
  `relate_company_type` int(11) NULL COMMENT ""关联公司类型(0:柏鹿,1:左萦,2:西芮,3:柏鹿,99:所有)"",
  `search_detail` varchar(65533) NULL COMMENT ""活动搜索信息"",
  `store_platform` int(11) NULL COMMENT ""店铺平台类型(0:全部,1:美团,2:饿了么,3:京东)"",
  `jd_status` int(11) NULL COMMENT ""京东状态(1:开启活动,0:未开启)"",
  `jd_order_amt` decimal(12, 2) NULL COMMENT ""京东订单金额"",
  `jd_rebate_amt` decimal(12, 2) NULL COMMENT ""京东返利金额"",
  `jd_promotion_quota` int(11) NULL COMMENT ""京东活动名额"",
  `jd_promotion_remain_quota` int(11) NULL COMMENT ""京东活动剩余名额"",
  `jd_upload_num` int(11) NULL COMMENT ""京东待上传数量"",
  `jd_audit_num` int(11) NULL COMMENT ""京东待审核数量"",
  `jd_finished_num` int(11) NULL COMMENT ""京东完成数量"",
  `jd_mlabel_rebate_amt` decimal(12, 2) NULL COMMENT ""京东餐标返现金额"",
  `store_product_id` int(11) NULL COMMENT ""同dwd_sr_store_danpin 字段danpin_id""
) ENGINE=OLAP 
PRIMARY KEY(`store_promotion_id`, `dt`)
COMMENT ""外卖活动表""
PARTITION BY date_trunc('month', dt)
DISTRIBUTED BY HASH(`store_promotion_id`)
ORDER BY(`dt`, `store_promotion_id`)
PROPERTIES (
""compression"" = ""LZ4"",
""enable_persistent_index"" = ""true"",
""fast_schema_evolution"" = ""false"",
""replicated_storage"" = ""true"",
""replication_num"" = ""3""
);"




"CREATE TABLE `dim_silkworm_user` (
  `user_id` bigint(20) NOT NULL COMMENT ""用户ID"",
  `create_time` datetime NOT NULL COMMENT ""创建时间"",
  `update_time` datetime NULL COMMENT ""更新时间"",
  `user_wechat_id` int(11) NULL COMMENT ""用户微信ID"",
  `inviter_user_id` int(11) NULL COMMENT ""邀请用户ID"",
  `user_nickname` varchar(65533) NULL COMMENT ""用户昵称"",
  `user_avatar_url` varchar(65533) NULL COMMENT ""用户头像地址"",
  `gender` varchar(65533) NULL COMMENT ""性别(未知,男,女)"",
  `birthday` varchar(65533) NULL COMMENT ""生日"",
  `phone` varchar(65533) NULL COMMENT ""手机号"",
  `user_real_name` varchar(65533) NULL COMMENT ""用户真实姓名"",
  `await_withdrawal_candou_num` decimal(12, 2) NULL COMMENT ""待提现蚕豆数"",
  `user_meal_ticket_num` int(11) NULL COMMENT ""用户饭票量"",
  `withdrawal_candou_num` decimal(12, 2) NULL COMMENT ""提现中蚕豆数"",
  `accu_valid_order_num` int(11) NULL COMMENT ""累计有效订单量"",
  `status` int(11) NULL COMMENT ""用户状态(0:未封号,1:封号)"",
  `register_time` varchar(65533) NULL COMMENT ""注册时间"",
  `valid_team_user_num` int(11) NULL COMMENT ""有效团员数"",
  `tot_withdrawal_amt` decimal(12, 2) NULL COMMENT ""已提现总金额"",
  `eleme_user_id` varchar(65533) NULL COMMENT ""饿了么用户ID"",
  `is_meituan_auth_user` int(11) NULL COMMENT ""是否美团认证用户(0:否,1:是)"",
  `meituan_auth_user_detail` varchar(65533) NULL COMMENT ""美团认证用户详情"",
  `first_valid_order_time` varchar(65533) NULL COMMENT ""首次有效订单时间"",
  `latest_valid_order_time` varchar(65533) NULL COMMENT ""最近一次有效订单时间"",
  `block_release_time` varchar(65533) NULL COMMENT ""拉黑解除时间"",
  `homepage_popup_day_notify_time` varchar(65533) NULL COMMENT ""首页弹窗每日提醒时间"",
  `bind_interior_staff_wechat_id` int(11) NULL COMMENT ""绑定小蚕内部员工微信ID"",
  `bind_interior_staff_wechat_account` varchar(65533) NULL COMMENT ""绑定小蚕内部员工微信账号"",
  `wechat_qrcode_url` varchar(65533) NULL COMMENT ""微信QR码地址"",
  `is_auto_audit` int(11) NULL COMMENT ""是否开启自动审核(0:否,1:是)"",
  `meituan_union_link` varchar(65533) NULL COMMENT ""美团联盟链接"",
  `meituan_union_link_create_time` varchar(65533) NULL COMMENT ""美团联盟链接创建时间"",
  `meituan_union_action_id` int(11) NULL COMMENT ""美团联盟链接行为ID"",
  `latest_login_time` varchar(65533) NULL COMMENT ""最近一次登录时间"",
  `cityid_update_time` varchar(65533) NULL COMMENT ""城市ID更新时间"",
  `county_id` int(11) NULL COMMENT ""区县ID"",
  `city_id` int(11) NULL COMMENT ""城市ID"",
  `minipro_customer_message_receive_time` varchar(65533) NULL COMMENT ""小程序收到客服消息时间"",
  `minipro_customer_message_send_remain_num` int(11) NULL COMMENT ""小程序发送客服消息剩余次数"",
  `is_show_newuser_guide` int(11) NULL COMMENT ""是否展示新手指引(0:否,1:是)"",
  `latest_login_platform` varchar(65533) NULL COMMENT ""最近一次登录设备终端平台"",
  `app_platform` varchar(65533) NULL COMMENT ""APP端终平台"",
  `is_app_notify_open` int(11) NULL COMMENT ""是否app打开通知提醒(0:否,1:是)"",
  `lastd_valid_order_num` int(11) NULL COMMENT ""昨日有效订单量"",
  `latest_login_ip` varchar(65533) NULL COMMENT ""最近一次登录IP"",
  `is_whitelist` int(11) NULL COMMENT ""是否白名单(0:是,1:否)"",
  `alipay_account` varchar(65533) NULL COMMENT ""阿里支付账户"",
  `block_reason` varchar(65533) NULL COMMENT ""封禁原因"",
  `latest_login_app_version` varchar(65533) NULL COMMENT ""最近一次登录APP版本"",
  `unsatisfied_order_num` int(11) NULL COMMENT ""不满意订单量"",
  `is_interior_staff` int(11) NULL COMMENT ""是否小蚕内部员工(0:否,1:是)"",
  `bind_interior_staff_wework_id` int(11) NULL COMMENT ""绑定小蚕内部员工企业微信ID"",
  `bind_interior_staff_wework_account` bigint(20) NULL COMMENT ""绑定小蚕内部员工企业微信账号"",
  `latest_block_time` varchar(65533) NULL COMMENT ""最近一次拉黑时间"",
  `latest_reward_time` varchar(65533) NULL COMMENT ""最近一次奖励时间"",
  `user_risk_level` varchar(65533) NULL COMMENT ""用户风险等级"",
  `pass_unsatisfied_order_num` int(11) NULL COMMENT ""通过不满意订单数量"",
  `is_logoff` int(11) NULL COMMENT ""是否注销(0:否,1:是)"",
  `user_extra_point` int(11) NULL COMMENT ""用户额外积分(拉新/营销活动等获得)"",
  `alipay_user_id` varchar(65533) NULL COMMENT ""支付宝芝麻信用授权用户ID"",
  `user_id_num` varchar(65533) NULL COMMENT ""用户身份证号码"",
  `withdrawal_password` varchar(65533) NULL COMMENT ""提现密码"",
  `register_platform` varchar(65533) NULL COMMENT ""用户注册端""
) ENGINE=OLAP 
PRIMARY KEY(`user_id`)
COMMENT ""用户基础信息表""
DISTRIBUTED BY HASH(`user_id`)
ORDER BY(`user_id`)
PROPERTIES (
""compression"" = ""LZ4"",
""enable_persistent_index"" = ""true"",
""fast_schema_evolution"" = ""false"",
""replicated_storage"" = ""true"",
""replication_num"" = ""2""
);"


