select
    category_type, -- 一级类目ID
    sub_category_type, -- 二级类目ID
    category_id -- 三级类目ID
from dwd.dwd_sr_silkworm_explore_promotion
where dt>=date_sub(current_date(),interval 360 day)
    -- and str_to_date(begin_time,'%Y-%m-%d') between date_sub(current_date(),interval 30 day) and date_sub(current_date(),interval 1 day)
    and promotion_type in (1,4) -- 探店
group by 1,2,3;



select
    category_type as cate1, -- 一级类目ID
    case when category_type=1 then '正餐美食'
        when category_type=2 then '饮品小吃'
        when category_type=3 then '休闲玩乐'
        when category_type=4 then '生活服务'
        when category_type=5 then '快餐简餐'
        when category_type=6 then '火锅烧烤'
        when category_type=7 then '汉堡西餐'
        when category_type=8 then '亲子乐园'
    else '其他' end as cate1_name,
    sub_category_type as cate2, -- 二级类目ID
    case when sub_category_type=1 then '包子粥铺'
        when sub_category_type=2 then '汉堡西餐'
        when sub_category_type=3 then '火锅烧烤'
        when sub_category_type=4 then '快餐简餐'
        when sub_category_type=5 then '理发/男士'
        when sub_category_type=6 then '亲子/乐园'
        when sub_category_type=7 then '水果生鲜'
        when sub_category_type=8 then '甜品饮品'
        when sub_category_type=9 then '休闲/玩乐'
        when sub_category_type=10 then '炸串小吃'
        when sub_category_type=11 then '正餐/多人餐'
    else '其他' end as cate2_name,
    category_id as cate3, -- 三级类目ID
    case when category_id=1 then '包子粥铺'
        when category_id=2 then '面馆'
        when category_id=3 then '小吃快餐'
        when category_id=4 then '早茶'
        when category_id=5 then '汉堡西餐'
        when category_id=6 then '西餐'
        when category_id=7 then '火锅烧烤'
        when category_id=8 then '火锅'
        when category_id=9 then '烤肉'
        when category_id=10 then '烧烤烤串'
        when category_id=11 then '快餐简餐'
        when category_id=12 then '北京菜'
        when category_id=13 then '本帮江浙菜'
        when category_id=14 then '川菜'
        when category_id=15 then '创意菜'
        when category_id=16 then '东北菜'
        when category_id=17 then '东南亚菜'
        when category_id=18 then '韩国料理'
        when category_id=19 then '家常菜'
        when category_id=20 then '农家菜'
        when category_id=21 then '日本菜'
        when category_id=22 then '私房菜'
        when category_id=23 then '特色菜'
        when category_id=24 then '湘菜'
        when category_id=25 then '新疆菜'
        when category_id=26 then '鱼鲜'
        when category_id=27 then '粤菜'
        when category_id=28 then '自助餐'
        when category_id=29 then '理发/男士'
        when category_id=30 then 'SPA按摩'
        when category_id=31 then '熬夜修护'
        when category_id=31 then '补水保湿'
        when category_id=33 then '潮流染发'
        when category_id=34 then '防脱养发'
        when category_id=35 then '减肥瘦身'
        when category_id=36 then '紧致抗衰'
        when category_id=37 then '境外医美'
        when category_id=38 then '美白嫩肤'
        when category_id=39 then '美发'
        when category_id=40 then '美甲'
        when category_id=41 then '美睫'
        when category_id=42 then '美容/清洁'
        when category_id=43 then '美妆护肤'
        when category_id=44 then '祛痘'
        when category_id=45 then '头疗'
        when category_id=46 then '脱毛'
        when category_id=47 then '纹眉纹绣'
        when category_id=48 then '纹身'
        when category_id=49 then '舞蹈'
        when category_id=50 then '医学美容'
        when category_id=51 then '瑜伽/普拉提'
        when category_id=52 then '亲子/乐园'
        when category_id=53 then '冰雪海洋馆'
        when category_id=54 then '博物馆'
        when category_id=55 then '带娃泡汤'
        when category_id=56 then '电玩游戏'
        when category_id=57 then '儿童乐园'
        when category_id=58 then '儿童摄影'
        when category_id=59 then '儿童游泳'
        when category_id=60 then '公园植物园'
        when category_id=61 then '滑板轮滑'
        when category_id=62 then '击剑培训'
        when category_id=63 then '篮球培训'
        when category_id=64 then '母婴购物'
        when category_id=65 then '农家采摘'
        when category_id=66 then '亲子餐厅'
        when category_id=67 then '亲子活动'
        when category_id=68 then '亲子酒店'
        when category_id=69 then '亲子游泳'
        when category_id=70 then '体适能培训'
        when category_id=71 then '托班/托儿所'
        when category_id=72 then '演出/展览'
        when category_id=73 then '婴幼服务'
        when category_id=74 then '孕产服务'
        when category_id=75 then '孕妇摄影'
        when category_id=76 then '早教'
        when category_id=77 then '水果生鲜'
        when category_id=78 then '甜品饮品'
        when category_id=79 then '茶馆'
        when category_id=80 then '咖啡厅'
        when category_id=81 then '面包甜点'
        when category_id=82 then '食品滋补'
        when category_id=83 then '饮品店'
        when category_id=84 then '休闲/玩乐'
        when category_id=85 then 'DIY手工坊'
        when category_id=86 then 'KTV'
        when category_id=87 then 'Live House'
        when category_id=88 then '按摩/足疗'
        when category_id=89 then '茶馆'
        when category_id=90 then '儿童乐园'
        when category_id=91 then '健身中心'
        when category_id=92 then '酒吧'
        when category_id=93 then '剧本杀'
        when category_id=94 then '撸宠'
        when category_id=95 then '密室/沉浸'
        when category_id=96 then '棋牌室'
        when category_id=97 then '球类运动'
        when category_id=98 then '私人影院'
        when category_id=99 then '台球馆'
        when category_id=100 then '体育场馆'
        when category_id=101 then '团建/轰趴'
        when category_id=102 then '网吧/电竞'
        when category_id=103 then '洗浴/汗蒸'
        when category_id=104 then '新奇体验'
        when category_id=105 then '游乐游艺'
        when category_id=106 then '游泳馆'
        when category_id=107 then '桌面游戏'
        when category_id=108 then '炸串小吃'
        when category_id=109 then '螺蛳粉'
        when category_id=110 then '小龙虾'
    else '其他' end as cate3_name
from dwd.dwd_sr_silkworm_explore_promotion
where dt>=date_sub(current_date(),interval 365 day)
    and promotion_type in (1,4) -- 探店
    and store_promotion_name not regexp '测试'
group by 1,2,3,4,5,6;